import { useEffect,useMemo,useState } from "react";
import { Activity, ArrowDownRight, ArrowUpRight, BarChart3, Users } from "lucide-react";
import { analyticsApi } from "../../api/analyticsApi";
import type { CategorySpending, RecentActivity } from "../../types/analytics";

const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2});
const dateTime=new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"});
export default function AnalyticsPage(){
 const [spent,setSpent]=useState(0),[remaining,setRemaining]=useState<number|null>(null),[owe,setOwe]=useState(0),[owed,setOwed]=useState(0),[categories,setCategories]=useState<CategorySpending[]>([]),[activity,setActivity]=useState<RecentActivity[]>([]),[groups,setGroups]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const [s,r,o,od,c,a,g]=await Promise.all([analyticsApi.getSpentThisMonth(),analyticsApi.getBudgetRemaining(),analyticsApi.getYouOwe(),analyticsApi.getYouAreOwed(),analyticsApi.getSpendingByCategory(),analyticsApi.getRecentActivity(),analyticsApi.getOpenGroups()]);setSpent(s);setRemaining(r);setOwe(o);setOwed(od);setCategories(c);setActivity(a);setGroups(g);}catch(err:any){setError(err.response?.data?.message??"Couldn't load analytics.");}finally{setLoading(false);}}useEffect(()=>{load()},[]);
 const categoryTotal=useMemo(()=>categories.reduce((s,c)=>s+c.spent,0),[categories]);const budgetTotal=useMemo(()=>categories.reduce((s,c)=>s+c.budget,0),[categories]);
 if(loading)return <div className="finance-page"><div className="expense-skeleton">{[1,2,3,4,5].map(i=><div key={i}/>)}</div></div>;
 return <div className="finance-page"><section className="page-intro"><div><span className="header-kicker">Insights</span><h2>Analytics.</h2><p>A deeper view of the numbers SpendWise is tracking for you.</p></div><button className="button button-secondary" onClick={load}><Activity size={14}/> Refresh</button></section>
 {error&&<div className="inline-error"><BarChart3 size={15}/>{error}<button onClick={load}>Retry</button></div>}
 <section className="analytics-metrics"><Metric label="Spent this month" value={money.format(spent)} tone="negative"/><Metric label="Budget remaining" value={remaining===null?"No overall budget":money.format(remaining)} tone={remaining!==null&&remaining<0?"negative":"positive"}/><Metric label="You owe" value={money.format(owe)} tone="negative"/><Metric label="Owed to you" value={money.format(owed)} tone="positive"/></section>
 <section className="analytics-grid"><div className="analytics-panel"><div className="panel-head"><div><h3>Category spending</h3><p>Current budget period · {categories.length} tracked categories</p></div><BarChart3 size={18}/></div>{categories.length===0?<Empty text="No category budgets are active for the current period."/>:<div className="analytics-categories">{categories.map(c=>{const pct=c.budget?Math.min(100,(c.spent/c.budget)*100):0;return <div className="analytics-category" key={c.budgetId}><div className="analytics-category-head"><div><b>{c.categoryName}</b><span>{money.format(c.spent)} of {money.format(c.budget)}</span></div><strong>{Math.round(pct)}%</strong></div><div className="analytics-track"><i style={{width:pct+"%"}}/></div></div>})}</div>}<div className="analytics-totals"><span>Tracked spending <b>{money.format(categoryTotal)}</b></span><span>Category limits <b>{money.format(budgetTotal)}</b></span></div></div>
 <div className="analytics-panel"><div className="panel-head"><div><h3>Open groups</h3><p>Groups with outstanding expense shares</p></div><Users size={18}/></div>{groups.length===0?<Empty text="No open group balances right now."/>:<div className="analytics-groups">{groups.map(g=><div className="analytics-group" key={g.groupId}><div><b>{g.groupName}</b><span>{g.openExpenseCount} open expense{g.openExpenseCount===1?"":"s"}</span></div><ArrowUpRight size={15}/></div>)}</div>}</div></section>
 <section className="analytics-panel"><div className="panel-head"><div><h3>Recent activity</h3><p>Financial activity from the last 7 days</p></div><Activity size={18}/></div>{activity.length===0?<Empty text="No recent activity in the last 7 days."/>:<div className="activity-list">{activity.map(item=><div className="activity-row" key={item.id}><span className={"activity-icon "+(item.amount>=0?"income":"expense")}>{item.amount>=0?<ArrowUpRight size={14}/>:<ArrowDownRight size={14}/>}</span><div><b>{item.title}</b><span>{item.type} · {dateTime.format(new Date(item.occurredAt))}</span></div><strong className={item.amount>=0?"amount-positive":"amount-negative"}>{item.amount>=0?"+":"−"}{money.format(Math.abs(item.amount))}</strong></div>)}</div>}</section>
 </div>;
}
function Metric({label,value,tone}:{label:string;value:string;tone:string}){return <article className="analytics-metric"><span>{label}</span><strong className={tone}>{value}</strong></article>}
function Empty({text}:{text:string}){return <div className="analytics-empty">{text}</div>}
