import { FormEvent, useEffect, useMemo, useState } from "react";
import { CalendarRange, Plus, Save, Trash2, WalletCards } from "lucide-react";
import { budgetApi } from "../../api/budgetApi";
import { categoryApi } from "../../api/categoryApi";
import type { Budget, CategoryBudgetItem } from "../../types/budget";
import type { Category } from "../../types/category";

const money = new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2});

export default function BudgetsPage(){
 const [budget,setBudget]=useState<Budget|null>(null);const[categories,setCategories]=useState<Category[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[editing,setEditing]=useState(false);
 async function load(){setLoading(true);setError("");try{const current=await budgetApi.getCurrent();setBudget(current);}catch(err:any){if(err.response?.status!==404)setError(err.response?.data?.message??"Couldn't load your current budget.");else setBudget(null);}finally{setLoading(false);}}
 useEffect(()=>{Promise.all([load(),categoryApi.getCategories("ALL").then(setCategories).catch(()=>setCategories([]))]);},[]);
 async function remove(){if(!window.confirm("Delete the current budget?"))return;try{await budgetApi.remove();setBudget(null);setEditing(false);}catch(err:any){setError(err.response?.data?.message??"Budget couldn't be deleted.");}}
 if(loading)return <div className="finance-page"><div className="expense-skeleton">{[1,2,3,4].map(i=><div key={i}/>)}</div></div>;
 return <div className="finance-page"><section className="page-intro"><div><span className="header-kicker">Planning</span><h2>Budgets.</h2><p>Set the limits that keep your spending intentional.</p></div>{budget&&<div className="budget-actions"><button className="button button-secondary" onClick={()=>setEditing(v=>!v)}><Save size={15}/>{editing?"Close editor":"Edit budget"}</button><button className="button button-danger" onClick={remove}><Trash2 size={15}/> Delete</button></div>}</section>
 {error&&<div className="inline-error"><WalletCards size={15}/>{error}<button onClick={load}>Retry</button></div>}
 {!budget&&!editing?<CreateBudgetForm categories={categories} onCreated={b=>{setBudget(b);setEditing(false)}}/>:budget&&editing?<BudgetEditor budget={budget} categories={categories} onSaved={b=>{setBudget(b);setEditing(false)}}/>:<BudgetEditor budget={null} categories={categories} onSaved={b=>{setBudget(b);setEditing(false)}}/>}
 {budget&&!editing&&<BudgetOverview budget={budget}/>}
 </div>;
}

function BudgetOverview({budget}:{budget:Budget}){const categoryTotal=useMemo(()=>budget.categoryBudgets.reduce((s,b)=>s+b.limit,0),[budget.categoryBudgets]);return <><section className="budget-summary"><article><span>Overall limit</span><strong>{budget.overallBudget===null?"—":money.format(budget.overallBudget)}</strong><small>Current budget period</small></article><article><span>Category limits</span><strong>{money.format(categoryTotal)}</strong><small>{budget.categoryBudgets.length} categories</small></article><article><span>Period</span><strong>{formatDate(budget.startDate)} → {formatDate(budget.endDate)}</strong><small>Active budget window</small></article></section><section className="budget-list-panel"><div className="panel-head"><div><h3>Category limits</h3><p>Individual limits inside this budget</p></div><CalendarRange size={18}/></div>{budget.categoryBudgets.length===0?<div className="table-empty"><b>No category budgets</b><span>This budget only has an overall limit.</span></div>:<div className="budget-category-list">{budget.categoryBudgets.map(item=><div className="budget-category-row" key={item.categoryName}><span className="category-card-icon">•</span><div><b>{item.categoryName}</b><small>Category budget</small></div><strong>{money.format(item.limit)}</strong></div>)}</div>}</section></>}

function CreateBudgetForm({categories,onCreated}:{categories:Category[];onCreated:(b:Budget)=>void}){return <BudgetEditor budget={null} categories={categories} onSaved={onCreated}/>}

function BudgetEditor({budget,categories,onSaved}:{budget:Budget|null;categories:Category[];onSaved:(b:Budget)=>void}){
 const [overall,setOverall]=useState(budget?.overallBudget?.toString()??"");const[start,setStart]=useState(budget?.startDate??new Date().toISOString().slice(0,10));const[end,setEnd]=useState(budget?.endDate??new Date().toISOString().slice(0,10));const[rows,setRows]=useState<CategoryBudgetItem[]>(budget?.categoryBudgets??[]);const[error,setError]=useState("");const[saving,setSaving]=useState(false);
 const categoryTotal=rows.reduce((s,r)=>s+(Number(r.limit)||0),0);const invalidOverall=overall&&categoryTotal>Number(overall);
 function addRow(){const available=categories.find(c=>!rows.some(r=>r.categoryName===c.name));if(available)setRows([...rows,{categoryName:available.name,limit:0}]);}
 function updateRow(index:number,key:"categoryName"|"limit",value:string){setRows(rows.map((row,i)=>i===index?{...row,[key]:key==="limit"?Number(value):value}:row));}
 function removeRow(index:number){setRows(rows.filter((_,i)=>i!==index));}
 async function submit(e:FormEvent){e.preventDefault();setError("");if(end<start){setError("End date cannot be before start date.");return}if(invalidOverall){setError("Category budgets cannot exceed the overall budget.");return}if(new Set(rows.map(r=>r.categoryName)).size!==rows.length){setError("Each category can only be added once.");return}setSaving(true);try{const payload={overallBudget:overall?Number(overall):undefined,categoryBudgets:rows.filter(r=>r.limit>0),startDate:start,endDate:end};const response=budget?await budgetApi.update(payload):await budgetApi.create(payload);onSaved(response);}catch(err:any){setError(err.response?.data?.message??"Budget couldn't be saved.");}finally{setSaving(false);}}
 return <form className="budget-editor" onSubmit={submit}><div className="budget-editor-head"><div><span className="header-kicker">{budget?"Edit current budget":"New budget"}</span><h3>{budget?"Tune your limits.":"Create your budget."}</h3></div><span>{budget?"Changes apply to the active budget period.":"Start date cannot be in the future."}</span></div><div className="budget-form-grid"><label>Overall budget<input type="number" min="0.01" step="0.01" value={overall} onChange={e=>setOverall(e.target.value)} placeholder="Optional"/></label><label>Start date<input type="date" value={start} onChange={e=>setStart(e.target.value)} max={new Date().toISOString().slice(0,10)}/></label><label>End date<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><div className="budget-category-head"><div><b>Category budgets</b><span>{money.format(categoryTotal)} allocated</span></div><button type="button" className="ghost-button" onClick={addRow}><Plus size={13}/> Add category</button></div>{rows.map((row,i)=><div className="budget-row" key={i}><select value={row.categoryName} onChange={e=>updateRow(i,"categoryName",e.target.value)}>{categories.filter(c=>c.name===row.categoryName||!rows.some((r,j)=>j!==i&&r.categoryName===c.name)).map(c=><option key={c.name}>{c.name}</option>)}</select><input type="number" min="0.01" step="0.01" value={row.limit||""} onChange={e=>updateRow(i,"limit",e.target.value)} placeholder="Limit"/><button type="button" onClick={()=>removeRow(i)}><Trash2 size={14}/></button></div>)}{!rows.length&&<div className="budget-no-categories">No category limits yet. Add one if you want category-level tracking.</div>}{error&&<div className="form-error">{error}</div>}<div className="expense-form-actions"><button type="submit" className="button button-primary" disabled={saving||!!invalidOverall}>{saving?"Saving...":budget?"Save changes":"Create budget"}</button></div></form>;
}
function formatDate(value:string){return new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(value+"T00:00:00"));}
