import { useEffect, useState } from "react";
import { ArrowDownLeft, ArrowUpRight, ChevronLeft, ChevronRight, CircleDollarSign, HandCoins, Users } from "lucide-react";
import { sharedFinanceApi } from "../../api/sharedFinanceApi";
import type { ExpenseShare, Settlement } from "../../types/shared";

const money = new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2});

export default function SharedPage(){
 const [shares,setShares]=useState<ExpenseShare[]>([]);const[settlements,setSettlements]=useState<Settlement[]>([]);const[tab,setTab]=useState<"shares"|"settlements">("shares");const[page,setPage]=useState(0);const[totalPages,setTotalPages]=useState(0);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 async function loadShares(){setLoading(true);setError("");try{setShares(await sharedFinanceApi.getMyShares());}catch(err:any){setError(err.response?.data?.message??"Couldn't load your expense shares.");}finally{setLoading(false);}}
 async function loadSettlements(next=page){setLoading(true);setError("");try{const r=await sharedFinanceApi.getMySettlements(next);setSettlements(r.content);setPage(r.page);setTotalPages(r.totalPages);}catch(err:any){setError(err.response?.data?.message??"Couldn't load settlements.");}finally{setLoading(false);}}
 useEffect(()=>{tab==="shares"?loadShares():loadSettlements(0);},[tab]);
 return <div className="finance-page"><section className="page-intro"><div><span className="header-kicker">Split & settle</span><h2>Shared finance.</h2><p>Track your outstanding shares and settlement history.</p></div></section>
 <div className="shared-tabs"><button className={tab==="shares"?"active":""} onClick={()=>setTab("shares")}><HandCoins size={15}/> My shares</button><button className={tab==="settlements"?"active":""} onClick={()=>setTab("settlements")}><CircleDollarSign size={15}/> Settlements</button></div>
 {error&&<div className="inline-error"><Users size={15}/>{error}<button onClick={()=>tab==="shares"?loadShares():loadSettlements(page)}>Retry</button></div>}
 {loading?<div className="expense-skeleton">{[1,2,3,4,5].map(i=><div key={i}/>)}</div>:tab==="shares"?<SharesList shares={shares}/>:<SettlementList settlements={settlements} page={page} totalPages={totalPages} onPage={loadSettlements}/>}
 </div>;
}
function SharesList({shares}:{shares:ExpenseShare[]}){if(!shares.length)return <div className="table-empty"><HandCoins size={22}/><b>No expense shares</b><span>Shared expenses assigned to you will appear here.</span></div>;return <section className="share-grid">{shares.map(share=><article className="share-card" key={share.id}><div className="share-card-top"><span className="transaction-icon"><Users size={15}/></span><span className={"status-pill "+share.status.toLowerCase()}>{share.status}</span></div><h3>{share.expenseTitle}</h3><div className="share-amounts"><div><small>Original share</small><b>{money.format(share.originalAmount)}</b></div><div><small>Remaining</small><b className={share.remainingAmount>0?"negative":"positive"}>{money.format(share.remainingAmount)}</b></div></div><div className="progress"><span style={{width:Math.min(100,Math.max(0,(1-share.remainingAmount/share.originalAmount)*100))+"%"}}/></div><small className="share-meta">{share.percentage}% share · Group {share.groupId.slice(0,8)}…</small></article>)}</section>}
function SettlementList({settlements,page,totalPages,onPage}:{settlements:Settlement[];page:number;totalPages:number;onPage:(p:number)=>void}){return <section className="expense-panel"><div className="table-head"><span><CircleDollarSign size={14}/> Settlement history</span><small>Newest first</small></div>{!settlements.length?<div className="table-empty"><CircleDollarSign size={22}/><b>No settlements</b><span>Your settlement history will appear here.</span></div>:<div className="expense-table-wrap"><table className="expense-table"><thead><tr><th>Payer</th><th>Receiver</th><th>Category</th><th>Status</th><th>Date</th><th className="amount-col">Amount</th></tr></thead><tbody>{settlements.map(s=><tr key={s.id}><td><b>{s.payerName}</b></td><td>{s.receiverName}</td><td>{s.categoryName}</td><td><span className={"status-pill "+s.status.toLowerCase()}>{s.status}</span></td><td>{new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(s.settledAt))}</td><td className="amount-col positive">{money.format(s.amount)}</td></tr>)}</tbody></table></div>}{totalPages>0&&<div className="pagination"><span>Page {page+1} of {totalPages}</span><div><button disabled={page===0} onClick={()=>onPage(page-1)}><ChevronLeft size={15}/></button><button disabled={page>=totalPages-1} onClick={()=>onPage(page+1)}><ChevronRight size={15}/></button></div></div>}</section>;}
